// <auto-generated />
using System;
using MVCBIG.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVCBIG.Migrations
{
    [DbContext(typeof(CampanyContext))]
    [Migration("20230807095330_inialCreating")]
    partial class inialCreating
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MVCBIG.Models.Depandent", b =>
                {
                    b.Property<int?>("ESSN")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("DEPENDENTNAME")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("BDATA")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmployeeSSN")
                        .HasColumnType("int");

                    b.Property<string>("RELATIONSHIP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ESSN", "DEPENDENTNAME");

                    b.HasIndex("EmployeeSSN");

                    b.ToTable("Depandents");
                });

            modelBuilder.Entity("MVCBIG.Models.Department", b =>
                {
                    b.Property<int>("Dnumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Dnumber"), 1L, 1);

                    b.Property<string>("DName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Dnumber");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("MVCBIG.Models.Dept_Loc", b =>
                {
                    b.Property<int>("Dnumber")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(2);

                    b.HasKey("Dnumber", "Location");

                    b.ToTable("Dept_Locs");
                });

            modelBuilder.Entity("MVCBIG.Models.Employee", b =>
                {
                    b.Property<int>("SSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SSN"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Dnumber")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<int?>("SuperSSN")
                        .HasColumnType("int");

                    b.HasKey("SSN");

                    b.HasIndex("Dnumber");

                    b.HasIndex("SuperSSN");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("MVCBIG.Models.Project", b =>
                {
                    b.Property<int>("PNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PNumber"), 1L, 1);

                    b.Property<int>("DNUM")
                        .HasColumnType("int");

                    b.Property<string>("PLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PNumber");

                    b.HasIndex("DNUM");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("MVCBIG.Models.Works_ON", b =>
                {
                    b.Property<int>("ESSN")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("PNO")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<int>("Hours")
                        .HasColumnType("int");

                    b.HasKey("ESSN", "PNO");

                    b.HasIndex("PNO");

                    b.ToTable("Works_ONs");
                });

            modelBuilder.Entity("MVCBIG.Models.Depandent", b =>
                {
                    b.HasOne("MVCBIG.Models.Employee", "Employee")
                        .WithMany("Dependents")
                        .HasForeignKey("EmployeeSSN");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("MVCBIG.Models.Dept_Loc", b =>
                {
                    b.HasOne("MVCBIG.Models.Department", "Department")
                        .WithMany("Locations")
                        .HasForeignKey("Dnumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("MVCBIG.Models.Employee", b =>
                {
                    b.HasOne("MVCBIG.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("Dnumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MVCBIG.Models.Employee", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SuperSSN");

                    b.Navigation("Department");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("MVCBIG.Models.Project", b =>
                {
                    b.HasOne("MVCBIG.Models.Department", "Department")
                        .WithMany("Projects")
                        .HasForeignKey("DNUM")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("MVCBIG.Models.Works_ON", b =>
                {
                    b.HasOne("MVCBIG.Models.Employee", "Employee")
                        .WithMany("Works_ON")
                        .HasForeignKey("ESSN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVCBIG.Models.Project", "Project")
                        .WithMany("Works_ON")
                        .HasForeignKey("PNO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("MVCBIG.Models.Department", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Locations");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("MVCBIG.Models.Employee", b =>
                {
                    b.Navigation("Dependents");

                    b.Navigation("Works_ON");
                });

            modelBuilder.Entity("MVCBIG.Models.Project", b =>
                {
                    b.Navigation("Works_ON");
                });
#pragma warning restore 612, 618
        }
    }
}
